[project]
name = "quickstart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible>=11.6.0",
    "ansible-dev-tools>=25.5.2",
    "requests>=2.32.3",
    "ruamel-yaml>=0.18.11",
]
